print("Maffile:")
print("\n")
litros = int(input("Quantos litros? "))
valor_do_leite = float(input("Valor do leite? ").replace(",", "."))
original_leite = 3.40
total = valor_do_leite - original_leite
lucro = total * litros
lucro_convertido = (f"{lucro:.2f}").replace(".", ",")
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Minaslandia debaixo")
print("\n")
litros2 = int(input("Quantos litros? "))
valor_do_leite2 = float(input("Valor do leite? ").replace(",", "."))
total2 = valor_do_leite2 - original_leite
lucro = total2 * litros2
lucro_convertido2 = (f"{lucro:.2f}").replace(".", ",")
print(f"Lucro: R${lucro_convertido2}")
print("-" * 30)
#####
print("Minaslandia de cima")
print("\n")
litros3 = int(input("Quantos litros? "))
valor_do_leite3 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Flor de maio")
print("\n")
litros4 = int(input("Quantos litros? "))
valor_do_leite4 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria Pão do dia")
print("\n")
litros5 = int(input("Quantos litros? "))
valor_do_leite5 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria Laura")
print("\n")
litros6 = int(input("Quantos litros? "))
valor_do_leite6 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria Monteiros")
print("\n")
litros7 = int(input("Quantos litros? "))
valor_do_leite7 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria do Moreira")
print("\n")
litros8 = int(input("Quantos litros? "))
valor_do_leite8 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria monalisa")
print("\n")
litros9 = int(input("Quantos litros? "))
valor_do_leite9 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria do Jaja")
print("\n")
litros10 = int(input("Quantos litros? "))
valor_do_leite10 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria General")
print("\n")
litros11 = int(input("Quantos litros? "))
valor_do_leite11 = float(input("Valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("República dos pães")
print("\n")
litros12 = int(input("Quantos litros? "))
valor_do_leite12 = float(input("Qual o valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Padaria alberto")
print("\n")
litros13 = int(input("Quantos litros? "))
valor_do_leite13 = float(input("Qual o valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
print("-" * 30)
#####
print("Chinelão")
print("\n")
litros14 = int(input("Quantos litros? "))
valor_do_leite14 = float(input("Qual o valor do leite? ").replace(",", "."))
print(f"Lucro: R${lucro_convertido}")
